name: Deploy

on:
  workflow_dispatch: 

env:
  AWS_REGION: eu-central-1               

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    strategy:
     matrix:
      node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'      
    - run: npm install                
    - run: npm run build --if-present

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.IAM_ROLE }}
        role-session-name: cicd-session
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: 900        
    - name: Upload to S3 Bucket
    # A local file will require uploading if the size of the local file is different than the size of the s3 object,
      run: |        
        aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET }}
    - name: Invalidate Cloudfront Distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"